# used to create the object
name: TreeGNN
device: cuda
mode: 'gripper_contact' # virtual_force or gripper_contact
randomize_target: True
heuristic_baseline: 'greedy' # random, greedy, root, or empty
data_root: "data"
test_data_name:  [
                  'graph_list_test_8_nodes_1k.pkl',
                  'graph_list_test_9_nodes_1k.pkl',
                  'graph_list_test_10_nodes_1k.pkl',
                  'graph_list_test_11_nodes_1k.pkl',
                  'graph_list_test_12_nodes_1k.pkl',
                  'graph_list_test_13_nodes_1k.pkl',
                  'graph_list_test_14_nodes_1k.pkl',
                  'graph_list_test_15_nodes_1k.pkl',
                  'graph_list_test_16_nodes_1k.pkl',
                  'graph_list_test_17_nodes_1k.pkl',
                  'graph_list_test_18_nodes_1k.pkl',
                  'graph_list_test_19_nodes_1k.pkl',
                  'graph_list_test_20_nodes_1k.pkl',
                  'graph_list_test_21_nodes_1k.pkl',
                  'graph_list_test_22_nodes_1k.pkl',
                  'graph_list_test_23_nodes_1k.pkl',
                  'graph_list_test_24_nodes_1k.pkl',
                  'graph_list_test_25_nodes_1k.pkl',
                  'graph_list_test_26_nodes_1k.pkl',
                  'graph_list_test_27_nodes_1k.pkl',
                  'graph_list_test_28_nodes_1k.pkl',
                  'graph_list_test_29_nodes_1k.pkl',
                  'graph_list_test_30_nodes_1k.pkl',
                  ]
# Virtual Force
#forward_model_ckpt_path: "runs/20230815_195014_forward_model_with_stiffness/best_model.pt"
#contact_policy_ckpt_path: "runs/20230816_100222_control_policy_final/best_model.pt"
# Gripper Trajectory
forward_model_ckpt_path: "runs/20230816_170955_control_policy_gripper_trajectory_8k_10cm/best_model.pt"
contact_policy_ckpt_path: "runs/20230817_081713_control_policy_gripper_trajectory_8k_10cm/best_model.pt"
model:
  hidden_size: 128
  num_IN_layers: 1
test:
  batch_size: 64
  visualize: False

