# used to create the object
name: TreeGNN
device: cuda
mode: 'gripper_contact' # virtual_force or gripper_contact
randomize_target: False
policy: 'gnn' # random, greedy, root, pointnet, or gnn
fully_connected: True
data_root: "data"
test_data_name:  [
                  'graph_list_test_10_nodes_1k.pkl',
                  'graph_list_test_11_nodes_1k.pkl',
                  'graph_list_test_12_nodes_1k.pkl',
                  'graph_list_test_13_nodes_1k.pkl',
                  'graph_list_test_14_nodes_1k.pkl',
                  'graph_list_test_15_nodes_1k.pkl',
                  'graph_list_test_16_nodes_1k.pkl',
                  'graph_list_test_17_nodes_1k.pkl',
                  'graph_list_test_18_nodes_1k.pkl',
                  'graph_list_test_19_nodes_1k.pkl',
                  'graph_list_test_20_nodes_1k.pkl',
                  'graph_list_test_21_nodes_1k.pkl',
                  'graph_list_test_22_nodes_1k.pkl',
                  'graph_list_test_23_nodes_1k.pkl',
                  'graph_list_test_24_nodes_1k.pkl',
                  'graph_list_test_25_nodes_1k.pkl',
                  'graph_list_test_26_nodes_1k.pkl',
                  'graph_list_test_27_nodes_1k.pkl',
                  'graph_list_test_28_nodes_1k.pkl',
                  'graph_list_test_29_nodes_1k.pkl',
                  'graph_list_test_30_nodes_1k.pkl',
                  ]
# Pointnet
#forward_model_ckpt_path: "runs/20230827_232920_PointNet/best_model.pt"
#contact_policy_ckpt_path: "runs/20230828_220011_pointnet/best_model.pt"
# GNN
forward_model_ckpt_path: "runs/20230827_231059_GNN/best_model.pt"
contact_policy_ckpt_path: "runs/20230828_210611_GNN/best_model.pt"


model:
  hidden_size: 128
  num_IN_layers: 1
test:
  batch_size: 64
  visualize: False

