# used to create the object
name: TreeGNN
device: cuda
data_root: "data"
test_data_name:  [
                  #'graph_list_test_8_nodes_2k.pkl',
                  #'graph_list_test_9_nodes_2k.pkl',
                  #'graph_list_test_10_nodes_2k.pkl',
                  #'graph_list_test_11_nodes_2k.pkl',
                  #'graph_list_test_12_nodes_2k.pkl',
                  #'graph_list_test_13_nodes_2k.pkl',
                  #'graph_list_test_14_nodes_2k.pkl',
                  #'graph_list_test_15_nodes_2k.pkl',
                  #'graph_list_test_16_nodes_2k.pkl',
                  #'graph_list_test_17_nodes_2k.pkl',
                  'graph_list_test_18_nodes_2k.pkl',
                  #'graph_list_test_19_nodes_2k.pkl',
                  #'graph_list_test_20_nodes_2k.pkl',
                  #'graph_list_test_21_nodes_2k.pkl',
                  #'graph_list_test_22_nodes_2k.pkl',
                  #'graph_list_test_23_nodes_2k.pkl',
                  #'graph_list_test_24_nodes_2k.pkl',
                  #'graph_list_test_25_nodes_2k.pkl',
                  #'graph_list_test_26_nodes_2k.pkl',
                  #'graph_list_test_27_nodes_2k.pkl',
                  #'graph_list_test_28_nodes_2k.pkl',
                  #'graph_list_test_29_nodes_2k.pkl',
                  #'graph_list_test_30_nodes_2k.pkl',
                  ]
forward_model_ckpt_path: "runs/20230810_120237_main_forward_model_final/best_model.pt"
control_policy_ckpt_path: "runs/20230812_193859_cp_all_node_pred/best_model.pt"
model:
  hidden_size: 128
  num_IN_layers: 1
test:
  batch_size: 128
  visualize: False
