# used to create the object
name: final_gnn_architecture
device: cuda
mode: 'gripper_contact' # virtual_force or gripper_contact
policy: 'gnn' # random, greedy, root, pointnet, or gnn
fully_connected: True
data_root: "data"
train_data_name: [
                  "graph_list_11_nodes_6k.pkl",
                  "graph_list_13_nodes_6k.pkl",
                  "graph_list_15_nodes_6k.pkl",
                  "graph_list_17_nodes_6k.pkl",
                  "graph_list_19_nodes_6k.pkl",
                  ]
test_data_name:  [
                  "graph_list_10_nodes_1k.pkl",
                  "graph_list_12_nodes_1k.pkl",
                  "graph_list_14_nodes_1k.pkl",
                  "graph_list_16_nodes_1k.pkl",
                  "graph_list_18_nodes_1k.pkl",
                  "graph_list_20_nodes_1k.pkl",
                  ]
train:
  epochs: 1000000
  batch_size: 128
  learning_rate: 1e-3
  lam: 0.01
model:
  hidden_size: 128
  num_IN_layers: 5
logging:
  wandb: True